server:
  port: 9999
spring:
  application:
    name: uaa
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/changelog/master.xml
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
